name: Test

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main
      - develop
      - "*"
    tags-ignore:
      - "*"
    paths-ignore:
      - "**/*.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.4'

      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        env: 
          NNRMOE_TOKEN: ${{ secrets.NNRMOE_TOKEN }} 
        run: go test